version: "3"
services:
   nginx:
    build: 
          context: .
          dockerfile: nginx/Dockerfile
    container_name: nginx
    hostname: "lemp.incrys.com"
    ports: 
     - "8080:80"
    expose:
      - "80"
    volumes:
       - "./:/opt/app"
    tty: true
    stdin_open: true
    command: nginx

   php-fpm:
    build:
      context: .
      dockerfile: php/Dockerfile
    expose:
      - "9000"
    volumes:
      - "./:/opt/app"
    stdin_open: true
    tty: true
    command: php-fpm